operateur:
    resource: "@OperateurBundle/Controller/"
    type:     annotation
    prefix:   /


admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
    path: /api/login_check